pipeline {
    agent any
    
    environment {
        DOCKER_CREDENTIALS_ID = 'DOCKER_CREDENTIALS_ID' // Replace with your Docker Hub credentials ID
    }
    
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/nghia0coder/GYM93.git', credentialsId: 'github-access-token'
            }
        }
        
        stage('Build') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
                        def app = docker.build("itsnghiatime/gym93:v1.2", "-f GYM93/Dockerfile GYM93/")
                        app.push()
                    }
                }
            }
        }
        
        stage('Deploy') {
            steps {
                sshagent(['vps-ssh-key']) {
                    sh '''
                        ssh-keyscan -H 14.225.210.230 >> ~/.ssh/known_hosts
                        ssh -o StrictHostKeyChecking=no root@14.225.210.230 "
                            sudo docker pull itsnghiatime/gym93:v1.1
                            sudo docker stop gym93-webapp-1
                            sudo docker rm gym93-webapp-1
                            cd /home/gym93
                            sudo docker-compose up -d
                        "
                    '''
                }
            }
        }
    }
}