pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/nghia0coder/GYM93.git', credentialsId: 'github-access-token'
            }
        }
        
        stage('Build') {
            steps {
                sh 'docker build -t itsnghiatime/gym93:v1.1 -f GYM93/Dockerfile GYM93/'
                sh 'docker push itsnghiatime/gym93:v1.1' // Ensure the image is pushed to the registry
            }
        }
        
        stage('Deploy') {
            steps {
                sshagent(['vps-ssh-key']) {
                    sh '''
                        ssh-keyscan -H 14.225.210.230 >> ~/.ssh/known_hosts
                        ssh -o StrictHostKeyChecking=no root@14.225.210.230 "
                            cd /home/gym93
                            docker-compose pull webapp
                            docker-compose up -d
                            sudo systemctl restart nginx
                        "
                    '''
                }
            }
        }
    }
}